# Generated by Django 2.2 on 2020-03-12 13:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200308_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(default='test:'),
            preserve_default=False,
        ),
    ]
